### ISSUE TITLE
Reconciler ignores new ApplicationGroups or updates to existing ones sporadically

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#116]
Noticed a couple of times that the reconciler completely ignores a newly created ApplicationGroups or any updates made to an existing one.

**Comment by jonathan-innis** [comment]
We need a repro of this issue, this isn't specific enough to really be actionable. If you have more information @nitishm, please add it. Otherwise, we should consider closing this issue.

**Comment by nitishm** [comment]
Haven't seen this in a while. Closing it for now. Will reopen if we see it again.
