### ISSUE TITLE
Getting this 'skipping unknown hook: "crd-install"', while installing Orkestra

### ISSUE THREAD

**Issue by DS00528024** [Azure/Orkestra#123]
Hello All,

Any clue will be really helpful

helm install orkestra chart/orkestra/ --namespace orkestra --create-namespace -- giving below-mentioned issues

https://user-images.githubusercontent.com/65676105/112304159-2ad44d80-8cc3-11eb-8b39-9327ab4edcc7.png
![image](https://user-images.githubusercontent.com/58288579/112305031-36744400-8cc4-11eb-9419-6defde075ab4.png)

**Comment by nitishm** [comment]
This is a helm3 warning. Helm2 relies on hook: crd-install to install CRD resources before the other k8s resources. Helm3 however does this innately and is configured to spit this benign warning when the hook is encountered.
