### ISSUE TITLE
Add Developer Docs to Improve Local Testing

### ISSUE THREAD

**Issue by jonathan-innis** [Azure/orkestra#150]
Currently, there don't appear to be good docs around how to set-up a local environment for debugging. Building and pushing an image to docker is very inconvenient. It would be better if we provided documentation around how to get each piece set-up locally so that it's easier for contributors to start.

**Comment by nitishm** [comment]
@jonathan-innis Have you tried [Tilt](https://docs.tilt.dev/)? We have a [Tiltfile](https://github.com/Azure/Orkestra/blob/main/Tiltfile) checked in that can be used for development. 
However, it doesn't provide a debugging environment where you can run delve.
Another alternative would be to use [Okteto](https://okteto.com/docs/reference/development-environment) (via the VSCode [extension](https://okteto.com/blog/remote-kubernetes-development/))

We can include the documentation around using these two tools and provide the configuration files for the same.

**Comment by nitishm** [comment]
This might be a good place to add the instructions https://github.com/Azure/Orkestra/blob/main/docs/DEVELOPMENT.md

**Comment by jonathan-innis** [comment]
Yeah, I will give those a shot and see what works/makes the most sense. 

I have been using the VSCode debugger on the controller runtime running locally and that works great. Issue is more on the dependency side which running a debugger on an image in cluster might solve.
