### ISSUE TITLE
Reconcile ApplicationGroup at scheduled interval after success to watch for changes/failures to HelmReleases

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#156]
We want to support reconciliation that happens on a periodic basis after a primary success to watch for changes to the status of the generated `HelmReleases` similar to how it is done in helm-controller 
See https://toolkit.fluxcd.io/components/helm/helmreleases/#specification 
```go
type HelmReleaseSpec struct {
    ...
    // Interval at which to reconcile the Helm release.
    // +required
    Interval metav1.Duration `json:"interval"`
    ...
```

**Comment by nitishm** [comment]
@jonathan-innis any suggestions on supporting this?

**Comment by jonathan-innis** [comment]
A couple options that come to mind here:
1. We can just have a watch on the underlying `HelmRelease` to automatically re-reconcile when there is an update to the underlying `HelmRelease` status
2. We can pass a value to `ctrl.Result{requeueAfter: spec.Interval}, nil` to have the reconciler re-reconcile after the given time passed by the user

**Comment by nitishm** [comment]
> A couple options that come to mind here:
> 
> 1. We can just have a watch on the underlying `HelmRelease` to automatically re-reconcile when there is an update to the underlying `HelmRelease` status
> 2. We can pass a value to `ctrl.Result{requeueAfter: spec.Interval}, nil` to have the reconciler re-reconcile after the given time passed by the user

The latter sounds like a better approach. The former would result in a lot of reconciliation events on the application group as the associated HelmReleases go through transitions. Also IIRC status updates don't trigger reconciles (unless there is some setting that I might not be aware of)

**Comment by jonathan-innis** [comment]
You can setup the controller to have the underlying objects that the reconciler owns to re-reconcile on any updates (including status) but, in either case, it might make more sense to just perform a poll at a given interval that the user sets

**Comment by jonathan-innis** [comment]
Assigning to myself if that's cool @nitishm
