### ISSUE TITLE
Argo marked as optional but E2E testing requires Argo for some test cases

### ISSUE THREAD

**Issue by AH-Dietrich** [Azure/orkestra#180]
Looking through the Orkestra website and docs it shows Argo as an optional tool, but the current E2E testing uses Argo part of the validation. It checks the Argo workflow to see if the bookinfo workflow was successful. Should we change the argo testing as optional or change the docs to say its required?

**Comment by nitishm** [comment]
@AH-Dietrich since it is only used in the CI pipeline for e2e testing and not required during production we can leave it marked as optional
