### ISSUE TITLE
Inconsistent Garbage Collection with BookInfo Application

### ISSUE THREAD

**Issue by AH-Dietrich** [Azure/orkestra#198]
Noticing that the BookInfo application sometimes will not get garbage collected after successful deployment. Expected behavior is that all BookInfo pods should be removed upon success. This occurs for me when BookInfo fails to deploy, then I retry it, it succeeds, and all BookInfo pods stay up.

Steps to reproduce: 
* Deploy the BookInfo applicationgroup `kubectl apply -f examples/simple/bookinfo.yaml` 

* Get BookInfo to fail. (To force a failure I have tried turning off internet access to get an image pull error while trying to deploy)

* Remove BookInfo pods

* Delete BookInfo application group `kubectl delete applicationgroup bookinfo`

* Deploy BookInfo group again, allow it to successfully install

* Upon Success bookinfo will stay running with no garbage collection

**Comment by nitishm** [comment]
Tests have confirmed that this works in the latest release
