### ISSUE TITLE
Helm `uninstall` doesn't remove the HelmReleases that come with ApplicationGroup

### ISSUE THREAD

**Issue by jonathan-innis** [Azure/orkestra#222]
**Describe the bug**
Performing a `helm uninstall` of Orkestra after onboarding an `ApplicationGroup` doesn't remove the individual `HelmReleases` that are brought with the ApplicationGroup

**To Reproduce**
1. Perform a `helm install` with `helm install orkestra ./charts/orkestra -n orkestra --generate-namespace`
2. Apply an ApplicationGroup to the cluster with `kubectl apply -f config/samples/bookinfo.yaml`
3. Remove the Orkestra helm release with `helm uninstall orkestra -n orkestra`

**Expected behavior**
Helm should completely cleanup the resources or at least, we should provide an option to users to be able to choose whether they want their ApplicationGroup, HelmReleases, etc. removed with `helm uninstall`

Compare this with the `.spec.suspend` field that is used in the Flux2 project. This probably needs more discussion on whether this is an actual or whether we should use the default helm behavior which is to leave the CRDs and the underlying CRs

**Comment by nitishm** [comment]
So the CRDs don't get deleted either during uninstall? Flux.io CRDs, Argo CRDs and Orkestra CRDs

**Comment by jonathan-innis** [comment]
That is correct, that's helm's behavior for CRDs in the `crd/` directory. It just doesn't touch them because it would rather avoid breaking anything. We can still achieve this with hooks obviously

**Comment by jonathan-innis** [comment]
Let's discuss in standup tomorrow what we want this behavior to be

**Comment by jonathan-innis** [comment]
Won't fix
