### ISSUE TITLE
ConvertToDNS1123 helper function should also validate and fix other special characters, max len and starts-with rules that are not compatible 

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#252]
Instead of just replacing `_` with `-` that we do in the function we should do something akin to https://gitlab.com/gitlab-org/gitlab-runner/-/blob/0e2ae0001684f681ff901baa85e0d63ec7838568/executors/kubernetes/util.go#L268
However, rather than replacing all violating chars with `""` as in done in the above snippet, we always replace them with `-`

**Comment by nitishm** [comment]
@sanskriti-s take a stab at this one. The function can be found [here](https://github.com/Azure/orkestra/blob/main/pkg/helpers.go#L5)

The docs for running and testing for contributors can be found [here](https://azure.github.io/orkestra/developers.html)

**Comment by mahalrs** [comment]
@nitishm I will work on this.

**Comment by nitishm** [comment]
> @nitishm I will work on this.

Go for it!!
