### ISSUE TITLE
Can we distinguish between `Reversing` due to error and `Terminating` due to a delete

### ISSUE THREAD

**Issue by rramankutty0** [Azure/orkestra#254]
Can we distinguish between `Reversing` due to error and `Terminating` due to a delete? 
When I delete the `applicationGroup` I'm seeing `DEPLOY=Succeeded` and  `READY=Reversing`; can we shown this as Terminating?
Typically, if I delete something, the resource goes to a Terminating state.

```
$ kubectl get applicationgroup.orkestra.azure.microsoft.com -A
NAME             DEPLOY      READY       MESSAGE                                                        AGE
smf-federation   Succeeded   Reversing   workflow reversing because of helmreleases during install...   15m
```

**Comment by jonathan-innis** [comment]
Agreed, we need to have a more extended discussion about the Conditions that we return and the different states that they should be in under different scenarios, @rramankutty0 I will open a discussion to have a larger conversation around this

**Comment by nitishm** [comment]
Moved to https://github.com/Azure/orkestra/discussions/264
