### ISSUE TITLE
Update operators section in docs to include the latest helm-controller chart options 

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#260]
The current docs are out of date, in which they still reference the helm-operator values. We now use a custom helm chart for helm-controller found at https://github.com/nitishm/charts/tree/main/helm-chart-sources/helm-controller

We need to update the docs with the values.yaml from the above source.

**Comment by mahalrs** [comment]
@nitishm I will work on this.

From what I understand, I think we want to update the ```helm-operator``` section in [```operators.md```](https://github.com/Azure/orkestra/blob/main/docs/operators.md) file with [```values.yaml```](https://github.com/nitishm/charts/blob/main/helm-chart-sources/helm-controller/values.yaml) (replacing everything under helm-operator section in operators.md file with values.yaml).

**Comment by nitishm** [comment]
Yes precisely!
