### ISSUE TITLE
Update docs with the latest ApplicationGroup spec in APi reference section

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#261]
ApplicationGroup spec should match the latest tag in the documentation. This requires referencing the specific tag's https://github.com/Azure/orkestra/blob/**{{ tag }}**/api/v1alpha1/appgroup_types.go

**Comment by jonathan-innis** [comment]
I feel like we should have auto-generation for a lot of this or just do something like the GitOps Toolkit docs to avoid to do extra work whenever there are API changes. 

https://fluxcd.io/docs/components/kustomize/kustomization/

**Comment by nitishm** [comment]
> I feel like we should have auto-generation for a lot of this or just do something like the GitOps Toolkit docs to avoid to do extra work whenever there are API changes.
> 
> https://fluxcd.io/docs/components/kustomize/kustomization/

I agree the latter is easier to deal with when upgrading. Let's do this!

**Comment by nitishm** [comment]
Done
