### ISSUE TITLE
E2E tests failing with v0.3.0 executor image

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#271]
**Describe the bug**

**To Reproduce**
1. Create ApplicationGroup '...'
2. Add another Application to the Spec '...'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Kubernetes Version [e.g. 1.21.0]
- Kubernetes Distro [e.g. AKS, GKE, etc.]
- Orkestra Version Tag
- Helm Version

**Additional context**

**Comment by jonathan-innis** [comment]
Closed by #267
