### ISSUE TITLE
Autogeneration of docs

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#305]
I feel like we should have auto-generation for a lot of this or just do something like the GitOps Toolkit docs to avoid to do extra work whenever there are API changes. 

https://fluxcd.io/docs/components/kustomize/kustomization/

_Originally posted by @jonathan-innis in https://github.com/Azure/orkestra/issues/261#issuecomment-846626048_

**Comment by mahalrs** [comment]
I'm working on this. [Kustomize API reference](https://github.com/fluxcd/kustomize-controller/blob/main/docs/api/kustomize.md) is using [gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs)
