### ISSUE TITLE
Add API docs generation to CI

### ISSUE THREAD

**Issue by mahalrs** [Azure/orkestra#307]
**Is your feature request related to a problem? Please describe.**
Add API docs generation to CI

Associated #311

**Comment by nitishm** [comment]
#311

**Comment by mahalrs** [comment]
> #311

CI push is getting rejected because it's a protected branch. Let me look into this. The repository that I tested it on didn't have protected branch. Let me fix it.

**Comment by nitishm** [comment]
Let me know if it needs a special SECRET/TOKEN and I or @jonathan-innis can create one for it.

**Comment by mahalrs** [comment]
@nitishm Can you close this. It's fixed through #311
