### ISSUE TITLE
Add Unit Testing to `src/pkg`

### ISSUE THREAD

**Issue by jonathan-innis** [Azure/orkestra#316]
**Is your feature request related to a problem? Please describe.**

Our code coverage in `controllers` package is pretty high but the code coverage in the packages in the `src/pkg` directory is pretty bad. We need to write unit tests for these pieces to increase our code coverage

**Comment by mahalrs** [comment]
I will work on this.

**Comment by nitishm** [comment]
Partially addressed by #316

**Comment by jonathan-innis** [comment]
@nitishm This is too large to be an "issue". We should break this into smaller tasks
