### ISSUE TITLE
Missing forward for Executor "custom" type 

### ISSUE THREAD

**Issue by vineetgarhewal** [Azure/orkestra#401]
Logic is missing to add a new custom executor type - 

https://github.com/Azure/orkestra/blob/363b8a8946ee9e453625f49afb077d952b70a14b/config/crd/bases/orkestra.azure.microsoft.com_applicationgroups.yaml#L311

https://github.com/Azure/orkestra/blob/2e25586451c2ba00cd1e4008578eb909c89240ec/pkg/executor/executor.go#L41

**Comment by nitishm** [comment]
@jonathan-innis can you take this up?
